# Service logs (here debug mode)
debug = true
traefikLogsFile = "/var/log/traefik/traefik.log"
logLevel = "DEBUG"

# Entrypoints
[entryPoints]
    [entryPoints.http]
    address = ":80"
#        [entryPoints.http.redirect]
#        entryPoint = "https"
#    [entryPoints.https]
#    address = ":443"
#        [entryPoints.https.tls]
        
# Access log
filePath = "/var/log/traefik/access.log"
format = "common"

# Admin dashboard
[web]
address = ":8080"

[file]
filename = "/etc/traefik/traefik.toml"
watch = true


# rules
[backends]
  [backends.backend1]
[backends.back_raspberrypi_api.servers.python_flask]
        url = "http://51.158.76.194:8000"
#        url = "http://z.zufferey.com"

  [backends.backend2]
    # ...

[frontends]
  [frontends.frontend1]
    backend = "backends.backend1"
    entrypoints = ["http", "https"]
    passHostHeader = true
#        [frontends.front_raspberrypi_api.routes.desktoplamp]
        rule = "Host:www.zuzuwp.ml"

  [frontends.frontend2]
  # ...






