www1.tototutu.ml#zf190426.1524
#---------------------------------------------------------
# Service logs (here debug mode)
#---------------------------------------------------------
logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[traefikLog]
    filePath = "/var/log/traefik/traefik.log"

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.foo]
  address = ":8080"

  [entryPoints.bar]
  address = ":8081"

# Activate API and Dashboard
[api]
entryPoint = "bar"
dashboard = true

[file]
  [backends]
    [backends.backend1]
      [backends.backend1.servers.server1]
      url = "http://163.172.161.67:8081"

  [frontends]
    [frontends.frontend1]
    entryPoints = ["foo"]
    backend = "backend1"
      [frontends.frontend1.routes.test_1]
      rule = "www1.tototutu.ml"

