#---------------------------------------------------------
# Service logs (here debug mode)
#---------------------------------------------------------
debug = true
traefikLogsFile = "/var/log/traefik/traefik.log"
logLevel = "DEBUG"


#---------------------------------------------------------
# Entrypoints
#---------------------------------------------------------
[entryPoints]
    [entryPoints.http]
    address = ":80"
#        [entryPoints.http.redirect]
#        entryPoint = "https"
#    [entryPoints.https]
#    address = ":443"
#        [entryPoints.https.tls]
        

#---------------------------------------------------------
# Admin dashboard
#---------------------------------------------------------
[api]
dashboard = true


#---------------------------------------------------------
# Configuration file
#---------------------------------------------------------
[file]
    filename = "/etc/traefik/traefik.toml"
    watch = true


#---------------------------------------------------------
# Backends rules
#---------------------------------------------------------
[backends]
    #-----------------------------------------------------
    # Dashboard traefik
    #-----------------------------------------------------
    [backends.traefik]
        [backends.traefik.servers.server0]
        url = "http://163.172.161.67:8080"

    #-----------------------------------------------------
    # Site1
    #-----------------------------------------------------
    [backends.backend1]
        [backends.backend1.servers.server0]
        url = "http://163.172.161.67:8001"

    #-----------------------------------------------------
    # Site2
    #-----------------------------------------------------
    [backends.backend2]
        [backends.backend2.servers.server0]
        url = "http://163.172.161.67:8002"


#---------------------------------------------------------
# Frontends rules
#---------------------------------------------------------
[frontends]
    #-----------------------------------------------------
    # Dashboard traefik redirection
    #-----------------------------------------------------
    [frontends.frontend0]
    backend = "traefik"
        [frontends.frontend0.routes.route0]
        rule = "Host:www.tototutu.ml"

    #-----------------------------------------------------
    # Site1 redirection
    #-----------------------------------------------------
    [frontends.frontend1]
    entrypoints = ["http", "https"]
    backend = "backend1"
    passHostHeader = true
        [frontends.frontend1.routes.route0]
        rule = "Host:www.tototutu.cf"

    #-----------------------------------------------------
    # Site2 redirection
    #-----------------------------------------------------
    [frontends.frontend2]
    entrypoints = ["http", "https"]
    backend = "backend2"
    passHostHeader = true
        [frontends.frontend2.routes.route0]
        rule = "Host:www.tototutu.gq"
