# Service logs (here debug mode)
debug = true
traefikLogsFile = "/var/log/traefik/traefik.log"
logLevel = "DEBUG"

# Entrypoints
[entryPoints]
    [entryPoints.http]
    address = ":80"
#        [entryPoints.http.redirect]
#        entryPoint = "https"
#    [entryPoints.https]
#    address = ":443"
#        [entryPoints.https.tls]
        
# Admin dashboard
[api]
dashboard = true

[file]
filename = "/etc/traefik/traefik.toml"
watch = true

# rules
[backends]
    [backends.backend1]
        [backends.backend1.servers.server0]
        url = "http://163.172.161.67:8001"
#                url = "http://z.zufferey.com"

#    [backends.backend2]
#        [backends.backend2.servers.server0]
#        url = "http://163.172.161.67:8002"
#                url = "http://51.158.76.194:8001"
#                url = "http://z.zufferey.com"



[frontends]
    [frontends.frontend1]
    entrypoints = ["http", "https"]
    backend = "backend1"
    passHostHeader = true
        [frontends.frontend1.routes.route0]
        rule = "Host:www.tototutu.cf"

#    [frontends.frontend2]
#    entrypoints = ["http", "https"]
#    backend = "backend2"
#    passHostHeader = true
#        [frontends.frontend2.routes.route0]
#        rule = "Host:www.tototutu.gq"
